### ISSUE TITLE
Consistent naming from Modeling

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#101]
### Problem

Subsequent versions of a model may have different names from prior publishes, causing issues down-stream; for example, during model Clones used in rigging.

### Motivation

When rigging (1) loads a model and (2) makes a local clone for deformation, the connection between the model and clone depends on the original name.

If the model model is later published with new names, Maya won't know how to re-create the connection between original and clone during its "Replace Reference" operation.

### Potential Solution

Append to the modeling workflow the act of (1) loading a prior publish, e.g. the latest one and (2) "drive" the prior published model with updated model.

The result is consistent naming and making explicit the act of adding or removing meshes from a model.

**Comment by mottosso** [comment]
Another solution, on publish record the names present in the model and use that to compare against a future developed model.

Potential disadvantage, it could put strain on the database if the number of meshes are great - e.g. 100,000 meshes.

```python
import sys
import uuid

data = []
for _ in range(100000):
  data.append("%s_PLY" % uuid.uuid4())

print(sys.getsizeof(data))
# 824464
```

That's ~800kb per version.

**Comment by BigRoy** [comment]
Closing this. 

This is not related to Avalon core but is a discussion that relates to a studio config. If you have any questions or want to continue discussion feel free to do so in this issue, but for now this issue will be closed to reduce redundant clutter.

---

As a side note though. Note that traversing an Alembic file solely for the full hierarchy of paths can be relatively quick (as it doesn't have to read the geometry). As such, if you wouldn't opt for comparing database differences you can always fall back to that. It's likely not as fast as searching against a database, but it doesn't require to duplicate the data.

For sake of clarity, here's an example that should be able to run directly inside Maya as that has the `alembic` Python package available by default.

```python
import alembic.Abc
    
def get_alembic_paths(filename):
    """Return all full hierarchy paths from alembic file"""

    # Normalize alembic path
    path = os.path.normpath(filename)
    path = path.replace("\\", "/")
    path = str(path)  # path must be string

    archive = alembic.Abc.IArchive(path)
    root = archive.getTop()

    paths = []
    iterator = list(root.children)

    for obj in iterator:
        
        path = obj.getFullName()
        paths.append(path)

        # Include children's children
        iterator.extend(obj.children)

    return paths
    
path = "/path/to/file.abc"
print get_alembic_paths(path)
# Example result:
# ['/head_GES', '/head_GES/head_GESShape']
```

As such, to find differences in hierarchy you could do:

```python
old = get_alembic_paths(old_file)
new = get_alembic_paths(new_file)

# Make sets for ease of use and optimization
old = set(old)
new = set(new)

# Let's debug what's newly created or what's gone now
created = new - old
print("Created hierarchy paths: {0}".format(list(created)))
removed = old - new
print("Removed hierarchy paths: {0}".format(list(removed)))
```

[More info about the Alembic python package see the original documentation](https://docs.alembic.io/python/examples.html)
