### ISSUE TITLE
Render Setting Family

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#104]
### Goal

Enable publishing of render settings.

Render settings include:

- Dimensions, e.g. 1280x720, square pixel format
- Renderer, e.g. Arnold, RedShift
- Render Settings, e.g. antialias samples, light bounce iterations
- ?

**Comment by mottosso** [comment]
@Stonegrund if you could have a think about what you might expect from loading a "Render Settings" asset for a given shot, and put together a list similar to the above that would help kickstart this feature.

It's possible the separation isn't practical and that we'd have to resort to #83 (Creator Templates) or a per-family Maya Default Scene etc.

**Comment by Stonegrund** [comment]
Dimensions, fps, renderCamera, naming prefix all should be setup within the project. 

However, the render engine settings should be loaded as a `Preset`.

Is it possible to have both `lookdev/render_master_scene` be published as a maya scene and not through a family_SET? Basically like a default scene or when we load `lookdev/render_master_scene` through the loader it opens a maya scene. 
So at both render and lookdev phase we should open a scene and load assets and not the other way. Because it can cause issues due to loading order. Just like you would want to load a model before a lookdev and not the other way around.

I am thinking that this is a step before we start to publish presets, lights and renderLayers as separate sets.

**Comment by Stonegrund** [comment]
Don't know if I should put this as a different issue but, the render outputs. At the moment in the 'master render scene' we can control how the naming convention and how they should be versioned, but only in the work folder for each shot. 
I would much rather have a separate render path:
```
project\
        f02_prod\
                 renders\
                         sh010\                           
                                %l\                              <----Name of Render Layer
                                    <version>\                   <----Same version as the current scene version
                                              %s.####.ext        <---- %s= Scene name to be able to track who and from whre it has been rendered 
```

I believe if this is set properly this will help to streamline the comp setup for 3D passes alot. We do have some scripts/gizmos that already can connect different *read* nodes, however, we have to locate the rendered files and do some manual preparations that should be able to be scripted. 

*The Goal* is to reduce amount of clicks.

**Comment by mottosso** [comment]
Thanks @Stonegrund, 

This I think is about publishing renders, which we should get into soon.

Publishing a rendered image sequence would involve automatically put it into the right directory with the right name, including version and naming convention.

Created an issue for it here: #112

**Comment by Stonegrund** [comment]
Great. I will look in to #112

**Comment by mottosso** [comment]
Found this!

- http://around-the-corner.typepad.com/adn/2017/01/how-to-importexport-render-setup-with-python.html

Looks like someone at Autodesk have been having the same idea and implemented something for it, albeit in Maya 2017.

Worst case, we can learn from their success/mistakes and more quickly build something that works.

**Comment by Stonegrund** [comment]
Nice. That sounds like that we could use :) Awesome!

**Comment by BigRoy** [comment]
Closing this.

This is not related to Avalon core but is a discussion that relates to a studio config. If you have any questions or want to continue discussion feel free to do so in this issue, but for now this issue will be closed to reduce redundant clutter.

---

I know that @mkolar has developed a `renderSetup` settings publish/load through Avalon for their [pype-config](https://github.com/pypeclub/pype). I'm not sure it's already in that repository, but if you're interested definitely take a peek there.
