### ISSUE TITLE
staticModel

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#105]
### Goal

Enable publish of static geometry for render, including shaders and texture information.

### Motivation

`model` lacks texture and shader information, `rig` is overly complex and `lookdev` introduces one too many steps to introducing color to a static model.

Primary use is for geometry used in an environment, geometry without need to deform or pass through any additional pipeline step, such as rigging.

### Implementation

A new family is introduced called `staticModel` to complement the existing `model`.

**Comment by BigRoy** [comment]
Closing this.

This is not related to Avalon core but is a discussion that relates to a studio config. If you have any questions or want to continue discussion feel free to do so in this issue, but for now this issue will be closed to reduce redundant clutter.
