### ISSUE TITLE
Live Context Switch

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#107]
### Goal

Reduce time taken to begin work on new asset.

### Motivation

Currently, working on an asset involves going through the launcher and booting up Maya from within a given task. Sometimes, an artist may work on many assets of very short turnaround, such as 5 assets an hour. In such cases, booting up Maya can become a bottleneck.

### Implementation

This is open for discussion, there are a few ways to go about it.

For example, there's a space in the bottom-left corner of the Maya window well suited for additional buttons.

![image](https://cloud.githubusercontent.com/assets/2152766/25084938/55d7f8e4-2357-11e7-9946-5c4b669333ed.png)

Buttons could look like the Maya icon and stacked vertically like this.

```
 __     __
|         |
| project |
|__     __|
 __     __
|         |
|  asset  |
|__     __|
 __     __
|         |
|  task   |
|__     __|
```

Each button opening a menu of available choices.

Alternatively, one might add it to the existing Mindbender menu at the top of the Maya window.

**Comment by BigRoy** [comment]
Visually I think this could be great.

Though regarding the current context and switching I do have some questions:

For this to work, do we need to refactor all `os.environ['AVALON_PROJECT']`  and other look ups for Avalon state in publishing, etc. to ise Session? Or do we want the Session to ensure it remains in sync with `os.environ`?

I believe currently we sometimes do: 
```python
current_asset = os.environ['AVALON_ASSET']
```

Should that be refactored to the session? :) Or the other way around, where a change to the session also updates the environment? (In the latter case you could never operate with multiple sessions in a python environment. Is that ok?)

**Comment by mottosso** [comment]
> or this to work, do we need to refactor all os.environ['AVALON_PROJECT'] and other look ups for Avalon state in publishing, etc. to ise Session?

Yes. Some things are already referencing this object, but they all should. This object should read from `os.environ` once, at startup, and then it's the main point of contact for state. Changing it would change the state, `os.environ` shouldn't affect anything.

That's the theory at least. There might be edge-cases where `os.environ` is still needed, but hopefully not!

**Comment by mottosso** [comment]
I would suggest starting small, changing things like the current asset. It would affect where the Creator gets it's default asset name. That'd make a good PR, and help us evaluate the visuals. The other slots can remain locked until they get an implementation, one at a time.

**Comment by BigRoy** [comment]
> I would suggest starting small, changing things like the current asset. It would affect where the Creator gets it's default asset name. That'd make a good PR, and help us evaluate the visuals. The other slots can remain locked until they get an implementation, one at a time.

Sure. For me actually the first step is to just set up an api to allow switching context to ensure it's even possible locally. :) I'm expecting switching project is too big of a leap, because that project might use a different `.toml` for the active application (which might set different plug-ins, etc.)

**Comment by mottosso** [comment]
Mm, so for projects, you could for example isolate such a change, for example by opening up the Loader under a different project to get a different asset. It wouldnt' affect the "overall" or "global" session, just for that particular instance of the Loader.

For more complex use, like switching the environment and loaded plug-ins and paths etc to a new project, that can wait I think.

**Comment by tokejepsen** [comment]
Was this not implemented with the Context Manager?

**Comment by BigRoy** [comment]
> Was this not implemented with the Context Manager?

Yes, the context manager does allow switching live inside a host. Closing this.
