### ISSUE TITLE
Multi-update

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#155]
### Goal

Enable update of multiple loaded assets at once.

### Implementation

The Manager GUI is expanded to facilitate multiple selection and the display of the version of each loaded container in a table-like view. Buttons are placed at the top to quickly load the latest or latest approved of anything

![image](https://user-images.githubusercontent.com/2152766/26840161-1da9d1ce-4add-11e7-95f5-35727cad9d71.png)

**Comment by BigRoy** [comment]
#205 Implements this.

**Comment by BigRoy** [comment]
> #205 Implements this.

This has been merged ages ago and is resolved. Note that currently for Maya you'll need to enable `AVALON_EARLY_ADOPTER` as an environment variable to have it expose the up-to-date scene manager and loaders, see [the issue regarding cleaning that up here #364](https://github.com/getavalon/core/issues/364)
