### ISSUE TITLE
Creator Plug-ins

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#157]
### Goal

Facilitate multiple workflows using the same pipeline. In this case, the ability to define families and Instance attributes.

### Motivation

Currently, the families available in core are pre-defined in `mindbender.pipeline.install()`. This means that for anyone else looking to use this pipeline, but have different requirements on what types of assets there are and what they represent, they would need to maintain a patch covering the underlying git commit.

It isn't elegant nor particularly sustainable as any underlying update could throw their customisation. In a word, there wouldn't be an API for the added labour.

This issue is about defining such an API.

### Implementation

Publishing is currently customised via [external Python modules](https://github.com/mindbender-studio/core/tree/bf0e5f5036225fe6be6fa1fed480b97cee64a96f/mindbender/plugins). Each module targets a given family and can be updated and refined without interfacing with the underlying pipeline. I'd like for creator plug-ins to do the same.

Each family is defined through documentation, such as [this.](https://mindbender-studio.github.io/2.0/#contract). 

Each Creator Plug-in then..

1. Implement a given family per application, such as `mindbender.model` for Maya, and how they are later discovered during publishing.
2. Define default attributes for said family, such as `startFrame` for `mindbender.animation`
3. Define default contents, such as top-level `ROOT` group and associated object sets such as `out_SET` for `mindbender.rig`

The overall life-cycle for data in the pipeline then looks like this.

![image](https://user-images.githubusercontent.com/2152766/26918695-f63f8332-4c2a-11e7-9cb2-9b3f6562fbde.png)

Where `writing` is publishing and `reading` is loading.

Where each component is customisable via plug-ins, external to the underlying pipeline implementation. These plug-ins are then to be externalised further into an individual Git repository in which case the entirety of custom behaviour is external and swappable (potentially even at run-time).

**Comment by mottosso** [comment]
This also addresses #83.

**Comment by BigRoy** [comment]
Note that the problem of #181 still is something to take note of when implementing this issue. Specifically the need to "order" the custom attributes and the data. For example `start_frame` and `end_frame` and `step` I expect to be ordered after each other to have a sensible order for the artist. Currently this is being randomly ordered because they are in a `dict`.

**Comment by mottosso** [comment]
Yeah, I expect that to be handled directly in the plug-in, something like this.

```python
cmds.addAttr("name_of_instance", "some_attr1", "some_value")
cmds.addAttr("name_of_instance", "some_attr2", "some_value")
cmds.addAttr("name_of_instance", "some_attr3", "some_value")
```

It would make it difficult/impossible to read those values from another tool - for example, to visualise or customise them before entry - and I expect us to cross that bridge once we get to it.

**Comment by BigRoy** [comment]
With Creator classes implemented, should this be closed? Or are we keeping this open for a reason?

**Comment by mottosso** [comment]
No this is done!
