### ISSUE TITLE
Organising the loader, Assets

### ISSUE THREAD

**Issue by CalleHalldin** [getavalon/core#167]
**Goal**

Organizing the loader and create groups/containers for different assets types

**Movtivation**

With many shots and assets can make the loader become cluttered and less clear/intuitive.

**Implementation**
Divide the Film and Assets so they are completely separate from each other.
Group assets type together.

**Disclaimer** Bad paint image, This is not nice and not how i want to look :) but to give you an idea of what mean. if someone feel decent at designing a GUI, feel free to make a better mockup.
![loader2](https://user-images.githubusercontent.com/25660084/26932991-913925e8-4c65-11e7-91fc-6c594c3123d3.jpg)

**Comment by mottosso** [comment]
Related to #30

**Comment by mottosso** [comment]
Implemented.
