### ISSUE TITLE
Surface intersections identification tools

### ISSUE THREAD

**Issue by HenrikSkymne** [getavalon/core#177]
**Goal:**
Make it easier and faster to spot and correct surface intersections that causes render issues when using sub Surface scattering.

**Motivation:**
Complex rigs that have surfaces that uses sub Surface scattering are sensitive to intersections between meshes.
The rigs cannot be bullet proof against this without becoming overly complex, and animators have a hard time seeing where this effect happens.
Often the issues are only spotted upon render and it would be beneficial to be able to spot these issues earlier.
If these issues can be spotted directly when animating the animator can avoid or correct poses that will later on cause issues.
If issues can easily be spotted without expensive renders time can be saved.

**implementation**
Several possible Tools could be made to facilitate in locating these issues:

- A shader, cgfx or other, that locates these issues. 
The light inside a proper working SSS model will work as this: Light hits facing poly, Light hits rearwards facing poly, repeat.
The light inside a Surface where shapes intersect will work as this: Light hits facing poly, light hits facing poly, light hits rearwards facing poly. In this instance the entry Point for the light could be highlighted to show an issue with intersections by flagging the Surface in a contrasting color.
For this to work care would have to be taken to make sure all SSS items in the scene are evaluated at the same time, as characters are often made by many different objects, and many shader solutions work on object by object basis. Care also needs to be taken to include non SSS objects where they intersect.

- Quick render with SSS solution.
A complement or replacement for a realtime shader that will still reduce the later render times would be to have a quick implement SSS render that highlights issues.
Objects should assigned either SSS or non SSS material properties. Shaders would be assigned for a quick render pass that is not meant for final render, but only to isolate the future intersection issues. Again, a solution that uses contrasting colors to highlight the issues would be beneficial.

- Mesh intersection indentification.
Tools that does not work on a shader level, but on model basis, that isolates and displays where intersections happen, would serve the same purpose. Again, care needs to be taken to only do this on SSS Surfaces.

**Comment by mottosso** [comment]
Here's what I showed Calle a while back.

![untitled project](https://user-images.githubusercontent.com/2152766/27021952-8d0538c8-4f43-11e7-84d2-1525ef1c75f2.gif)

**Careful, this clears your current scene**

```python
from maya import cmds, mel

cmds.file(new=True, force=True)
cube, _ = cmds.polyCube()
sphere, _ = cmds.polySphere()
cmds.move(1, 0, 0, cube)

cmds.select([cube, sphere])
mel.eval("assignNewPfxToon")

for attr, value in {"intersectionLines": 1,
                    "creaseLines": 0,
                    "profileLineWidth": 0,
                    "intersectionLineWidth": 4}.items():
    cmds.setAttr("pfxToonShape1." + attr, value)
```

**Comment by HenrikSkymne** [comment]
That does look interesting. If that can me made to a ready preset that can easily be turned on/off it is very useful. This should be tried on typical problem areas such as eyelids and mouth/teeth.

**Comment by CalleHalldin** [comment]
I tested that Marcus, works great, i even found a setting so it checked collision with it self. we should use this in the future for sure.

**Comment by HenrikSkymne** [comment]
Can this be made to be an easy to use tool?
Select object(s), click button and its activated?
Can it be made part of the mindbender toolset?

**Comment by mottosso** [comment]
Here's a script you can paste into your Script Editor, and then drag/drop into your Shelf to apply this to your current selection.

```python
from maya import cmds, mel

def apply_intersection_line():
    before = cmds.ls("pfxToonShape*")
    mel.eval("assignNewPfxToon")
    after = cmds.ls("pfxToonShape*")
    
    try:
        new = list(set(after) - set(before))[0]
    except IndexError:
        # No new line was created, you should have gotten a warning about it.
        return
    
    for attr, value in {"intersectionLines": 1,
                        "creaseLines": 0,
                        "profileLineWidth": 0,
                        "intersectionLineWidth": 4}.items():
        cmds.setAttr(new + "." + attr, value)


apply_intersection_line()
```

**Comment by HenrikSkymne** [comment]
Yes, but can we make that into a proper tool on the mindbender pipeline so people dont have to do this per user? A great tool is readily available.

**Comment by mottosso** [comment]
Definitely, this is meant more as a beta-test feature. Once you've tried it out, I expect you'll find various issues and additional things you'd like for it. At that point, return here and make a note of it and it'll be included into the tool distributed with the pipeline.

**Comment by tokejepsen** [comment]
@HenrikSkymne and @CalleHalldin, how did your testing go with this?

**Comment by tokejepsen** [comment]
I wonder whether you can do an automated check?

If the intersections lines are white and everything else is black, you could maybe analyse the percentage of white within a frame to determine how much intersection is present.

**Comment by tokejepsen** [comment]
Hope you don't mind @mottosso but I have made a tool from this idea; https://github.com/tokejepsen/intersections-tool

**Comment by mottosso** [comment]
Certainly not, that's a great idea!
