### ISSUE TITLE
Common project name

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#180]
### Goal

Find a name applicable to more than a single studio, other than `mindbender-core`.

**For example**

| Name        | Motivation
|:------------|:-------------
| Pypline     | Or `Pypeline`, because it's a pipeline written in Python
| Postline   | Pipeline for Post-production
| Wyrkflow | Something different
| Pithon      | Another spin on Pipeline and Python
| Avalon     | I love that name :)

Drop your suggestions here, don't forget to:

- Include **motivation**
- Google for it to make sure it isn't already a common name used by other software projects
- Think about how it'd be like to type it everyday, to read and talk about it.
- Have a look at whether the domain for said name is available, ideally `.com` but `.io` and others are also good.

**Comment by mottosso** [comment]
| Name        | Motivation
|:------------|:-------------
| Arpanet   | Global, interconnected, open source pipeline

It's epic, relevant in that it involves connecting many disparate pieces together, globally, I've got the [GitHub name](https://github.com/arpanet) and there isn't any software project that I'm aware of (apart from the [original 1969 tech](https://en.wikipedia.org/wiki/History_of_the_Internet#ARPANET)) in circulation today.

**Comment by mottosso** [comment]
| Name        | Motivation
|:------------|:-------------
| Mindline   | Short, unique, relevant to roots at Mindbender, sounds pleasant

**Comment by mottosso** [comment]
| Name        | Motivation
|:------------|:-------------
| vanilla       | Working title for MetaPipe's pipeline
| anypipe    | Previously used in Colorbleed

**Comment by BigRoy** [comment]
> anypipe | Previously used in Colorbleed

That's not what we used though; we had `cbra` (which was pronounced: "zebra").

**Comment by mottosso** [comment]
I'd say this is done. :)
