### ISSUE TITLE
Validate locked normals is buggy

### ISSUE THREAD

**Issue by BigRoy** [getavalon/core#183]
# Issue

The locked normal validation for meshes is currently not checking the full model if the transforms are in the instance as opposed to the shapes. The collector only includes the **direct set members** in the instance in Maya, as such if the `ROOT` group was in the instance, then none of its children are passed in the instance.

So history, children or parents are **not** included from the collect instance members.

# Problem

This introduces the problem where a Validator does not have access to the full hierarchy by just using the nodes in the instance. It'll need to retrieve the history, children or parents whenever it needs to check them. Just like how `maya.cmds.ls(instance, type="mesh")` wouldn't actually return in the related meshes in the **Validate Normals** plugin.

# Solution

The solution can be done in two ways:

- Either the validator retrieves the data from the scene; it finds the history, parents, or children that it needs to check. For example also include: `maya.cmds.listRelatives(instance, allDescendents=True, fullPath=True)` or for history checks do `maya.cmds.listHistory(instance)`.

> Note: these calls to list history or children can be slow in large scenes.

- Or the collector collects this additional data.

**Comment by mottosso** [comment]
Thanks @BigRoy.

I've added you and @aardschok as collaborators to this repo so that you can tag your issues with relevant labels. It also enables you to push to this repo, but please don't do that. Only pull-requests are supposed to make modifications.

**Comment by BigRoy** [comment]
> I've added you and @aardschok as collaborators to this repo so that you can tag your issues with relevant labels. 

Funnily enough I'm not able to edit any labels on issues.

**Comment by mottosso** [comment]
I think you might have to accept the invite first.

**Comment by BigRoy** [comment]
> I think you might have to accept the invite first.

Perfect; that was it. I missed that. I'm able to do so now.

**Comment by BigRoy** [comment]
Closing this since plug-ins have been removed. Continuing here: https://github.com/mindbender-studio/config/issues/3
