### ISSUE TITLE
Assign tasks per asset

### ISSUE THREAD

**Issue by BigRoy** [getavalon/core#185]
# Issue

Currently **tasks** are defined globally per project; there's a pre-specified list of tasks that can be initiated for any asset. This means any artist can initiate any task on any asset, for example starting *rigging on shot one*; likely unintended.`

Similarly as the artist works this means a long list is presented per asset as tasks.

# Proposal

The project specific task list is good to define a set of "predefined defaults" to be used in a project, but in most cases not all assets would need all of them. Simillarly, sometimes it's good to query what tasks are available for a specific asset; assigning the task to the asset.

As such I want to propose to add the **tasks** per asset in the database. 

This would allow some extra things:

- This would also allow us to just find the assets that have a *rigging* task or only the shots with a *comp* task.
- And, it would allow to separate the responsibility of initiating new tasks to a producer. For example the artist could only browse the assets and its *linked* tasks. It is then the producer who prior to this *enabled the task for that specific asset*.

In the database an extra field `tasks` could be added for assets that is a plain `list`, then to add a task:

```python
# psuedocode
import mindbender.io as io

asset = io.find_one({"type": "asset"})
if "model" not in asset['tasks']:
    asset['tasks'].append("model")
```

**Comment by mkolar** [comment]
Related to this... Is there any way currently to create custom tasks within the system? Say you have a big shot and want to split animation to 2 people one animating 'hero' and another one 'bg' chracters. In Ftrack we'd simply create 2 animation tasks with different name so each person can work on their own without interfering with the other.

**Comment by mottosso** [comment]
@mkolar Yes, you can either create two tasks, e.g. `bgAnimation` and `heroAnimation` (see PCAPI), or have both animators on the same task, but publish to different [subsets](https://getavalon.github.io/2.0/reference/#subset), e.g. `hero` and `bgHero`. If you wanted individual work files per artist, you can separate the folder layout by adding the `{user}` key to your folder template path (see `{user}` in PCAPI).

- [PCAPI](https://getavalon.github.io/2.0/reference/#project-configuration-api)

**Comment by mkolar** [comment]
> you can either create two tasks, e.g. bgAnimation and heroAnimation

However these are defined on a project basis aren't they? So all the shots would then have these two tasks? That's what it seems like anyways.

**Comment by mottosso** [comment]
> However these are defined on a project basis aren't they? So all the shots would then have these two tasks? That's what it seems like anyways.

That's right. It's a limitation at the moment. @BigRoy has been working on getting tasks parented to assets, I think that should work well. Would that work for you, you think?

**Comment by BigRoy** [comment]
> @BigRoy has been working on getting tasks parented to assets

Yes, we prefer  it that way too. We just assign a task to an asset. It's stored in the asset's `.data['tasks']` attribute. Next is for the launcher to support it too.

**Comment by BigRoy** [comment]
@mkolar We're now supporting this in the Avalon launcher too. It's not merged into the getavalon launcher yet though, but I'm expecting eventually it will. It will allow to set a specific list of tasks on an asset instead of showing all "statically" available ones of a project.

**Comment by BigRoy** [comment]
This should be available in core.

@mkolar was there anything you were still missing or had questions about?

@tokejepsen you played around with the tasks per asset too I recall. Was it now behaving the way you'd like?

**Comment by tokejepsen** [comment]
Yeah, the last time I looked at it the tasks per asset were working at expected :)

**Comment by davidlatwe** [comment]
I believe this definitely has been implemented and worked well now. (Second check after almost a year :laughing: )
