### ISSUE TITLE
Session() object for global state

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#189]
### Goal

Group global variables and state together into a single object.

### Motivation

At the moment, state is spread across at least three places.

1. Environment, e.g. `MINDBENDER_PROJECT`
2. Registry, e.g. `api.register_loader_path("c:\some\path")`
3. `io.py`, e.g. `io.activate_project("this_project")`

This makes it challenging to know what the current state is, which complicates tests and maintenance. Communicating and understanding state is also complicated.

Traces of leaked global state:

- [install()](https://github.com/mindbender-studio/core/blob/bb874e8fe34ab88f002b3d334190778a539eb8cf/mindbender/pipeline.py#L40)
- [Tests](https://github.com/mindbender-studio/core/blob/bb874e8fe34ab88f002b3d334190778a539eb8cf/mindbender/tests/test_pipeline.py#L41)
- [Tools](https://github.com/mindbender-studio/core/blob/bb874e8fe34ab88f002b3d334190778a539eb8cf/mindbender/tools/creator/app.py#L154)

### Implementation

Do what Python does.

Python uses environment variables for state as well, but not at run-time. Instead, it reads it *once* upon launch, and stores it internally. `PYTHONPATH` for example is parsed and stored as a list in `sys.path`.

On initialisation of the pipeline, look at the various sources supported, such as the environment, and build a Session object/dictionary containing all state. This is then used at run-time, and can be inspected during debugging, created during testing and replicated in order to simulate more than a single state; such as when browsing assets in one project from another.

```python
session = api.Session(
  project="Hulk",
  asset="Bruce",
  task="modeling",
  loaders="/path/to/loaders",
  creators="/path/to/creators"
)

for asset in session.find({"type": "asset"}):
  print(asset["name"])
```

**Comment by mottosso** [comment]
Or how about?

```python
session = api.Session(
  env={
    "project": "Hulk",
    "asset": "Bruce",
    "task": "modeling",
  },
  paths={
    "loaders": "/path/to/loaders",
    "creators": "/path/to/creators"
  }
)
```

**Comment by mottosso** [comment]
This has been implemented long ago, as `avalon.Session`.

**Comment by davidlatwe** [comment]
Does this related to [session.py](https://github.com/getavalon/core/blob/master/avalon/session.py) ?

**Comment by mottosso** [comment]
Thanks for pointing this out, I didn't think of it; by looks of it, that file has been deprecated.

https://github.com/getavalon/core/blob/c5577ac1f2e5af75de4454bfbb75f1f76a2b1ded/avalon/api.py#L26-L28

At a quick glance, the file doesn't appear used anywhere and looks safe to remove.
