### ISSUE TITLE
Exclude containers from publish

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#193]
### Goal

Enable publishing of nested assets, without including their metadata from load.

### Motivation

A "container" is a mechanism with which core can maintain information about what asset has been loaded, when, what version it was and by whom. They are used in the asset manager to visualise what has been loaded and to perform updates to it.

Currently, if there is a connection to a container at time of publish, it'll come along with the resulting file. What ends up happening is that when a user comes to load a published asset with a pre-existing container is that it shows up in the loader, alongside the originally loaded asset.

### Implementation

Either exclude any containers on publish, or filter them out in the loader.

Down the line, the intent is to have an asset reflect it's internal assets such that the user can e.g. update the model of a rig independently, without updating the rig. But this is not the approach for it, but rather have assets published and/or loaded more intelligently.

**Comment by BigRoy** [comment]
@mottosso this sounds like an implementation details of the mindbender-config you were working on at the time? Should this be closed?

**Comment by mottosso** [comment]
Yes, you are (probably) right. Likely a relic.
