### ISSUE TITLE
Supporting different "loads" than just references in Maya

### ISSUE THREAD

**Issue by BigRoy** [getavalon/core#217]
# Problem

Currently the Manager only supports managing references because the host api doesn't allow to work on the local content in different ways. In short, `avalon.maya.ls()` does not support different functionality. 

We should identify how one can extend this behavior and implement additional managing functionality, for example for _gpu caches_ in Maya.

### Additional notes

What makes this more complicated is the current `containerize` functionality in Maya. How would that translate to, for example, an imported gpu cache. A gpu cache is a "local scene object" and supports regular duplicating (ctrl + D), as such this breaks the containerized functionality as currently implemented. (Because suddenly there's much more in the container)

We'll need to define how we want the behavior to work in instances like that. In practice what does it mean in production to duplicate a gpu cache, in a way it's the exact same source file and nothing else changes. As such we should be able to track it exactly and it is "actually" already containerized (it is its own node type that is always a single node).

**Comment by mottosso** [comment]
No this isn't right.

The main purpose of `containerise` is to support non-references, as for references we could simply look at the reference-nodes themselves.

The resulting objectSet from `containerise` includes all nodes from a given loaded asset, including those you create yourself. The resulting container contains all newly created nodes, no matter how they were created.

This should work for gpuCache too.

Something I'm missing?

**Comment by mottosso** [comment]
Welcome to re-open!
