### ISSUE TITLE
Instance attributes parented under plugin attributes

### ISSUE THREAD

**Issue by aardschok** [getavalon/core#244]
## Issue
When creating an instance for any given family the attributes which are filled by the data are being added under the Arnold > Extra Attributes when Arnold is loaded.

![avalon_attr_in_arnold_extra_attrs](https://user-images.githubusercontent.com/26920875/28500890-e5982bbe-6fd0-11e7-9a09-a0189f0aba77.JPG)

The attributes are still accessible in the default manner `modelDefault.asset` etc. As for aesthetics I would be preferred to have it under the Maya Extra Attributes.

I have not yet encountered this bug when VRay is loaded

**Comment by mottosso** [comment]
Thanks @aardschok. This is a bug in 2017 for not just instances, but any attributes on objectSet type objects.

One workaround is to unload Arnold (`mtoa`).
