### ISSUE TITLE
Better 'locked scene' message in Maya

### ISSUE THREAD

**Issue by Sonegrund** [getavalon/core#245]
### GOAL
To make the message clearer and avoid confusion for new render artist.

### MOTIVATION
At the moment this may be bit confusing for new person to render a scene who as submitter a render scene and wants to save. It can be mistaken for a bug.
![image](https://user-images.githubusercontent.com/30410513/28525724-6ef836b0-7085-11e7-8f04-9713146de2ef.png)

### SUGGESTION
I would rather suggest a clearer message that pops up and tells the person who submitted a renderscene, that Avalon has prevented a newly submitted renderscene to override and save. This either on the same popup window or on submission from the Publisher or it could even automatically increment up. Perhaps the publisher could save a copy of the scene file where it published the renders as the render scenes are fairly small in file-size.

**Comment by mottosso** [comment]
Implemented in your the [Mindbender configuration](https://github.com/mindbender-studio/config/blob/49e32c66cc1fa7cf86540a2f61fc6f8b85646ef2/polly/maya/__init__.py#L95) (Maya API 1.0).

**Example**

```python
def before_save(return_code, _):
    """Prevent accidental overwrite of locked scene"""

    # Manually override message given by default dialog
    # Tested with Maya 2013-2017
    dialog_id = "s_TfileIOStrings.rFileOpCancelledByUser"
    message = ("Scene is locked, please save under a new name "
               "or run cmds.remove(\"lock\") to override")
    cmds.displayString(dialog_id, replace=True, value=message)

    # Returning false in C++ causes this to abort a save in-progress,
    # but that doesn't translate from Python. Instead, the `setBool`
    # is used to mimic this beahvior.
    # Docs: http://download.autodesk.com/us/maya/2011help/api/
    # class_m_scene_message.html#a6bf4288015fa7dab2d2074c3a49f936
    OpenMaya.MScriptUtil.setBool(return_code, not maya.is_locked())
```
