### ISSUE TITLE
Asset Loader - Columns are not sortable

### ISSUE THREAD

**Issue by aardschok** [getavalon/core#249]
## Issue

When trying to sort any item based on a column like `family` or `subset` nothing happens, see image.
![image](https://user-images.githubusercontent.com/26920875/28611736-1337d254-71ed-11e7-8c08-a28cca501ea3.png)

## Solution
Enable sorting in the view: `setSortingEnabled(True)`

**Comment by aardschok** [comment]
Solution is different than anticipated at first.
We will implement a proxy between the model and the view, this will help with solution of #250

**Comment by BigRoy** [comment]
Implemented with https://github.com/getavalon/core/pull/252
