### ISSUE TITLE
Manager fails to remove reference and linked container

### ISSUE THREAD

**Issue by aardschok** [getavalon/core#253]
issue #118 not working

Issue remains where container is left in the scene ad not properly removed when using `avalon.maya.pipeline.remove(container)`.

To reproduce the issue:
1. Reference in a few subsets through the Asset Loader
2. Remove a referenced subset through the Manager
3. Refresh the Manager to see the "removed" subset remains with the container name as objectName

![image](https://user-images.githubusercontent.com/26920875/28667022-f95fd3e4-72c9-11e7-8755-b9bd1264c320.png)

**Comment by aardschok** [comment]
## Proposition:
Query the linked container node of the referenceNode in question
```python
reference_node = "test_001_lookRN"
test = cmds.listConnections(reference_node, 
                                           destination=True,
                                           type="objectSet")
print test
[u'test_01__lookDefault__CON1']
```

**Comment by mottosso** [comment]
The thing currently responsible for deleting containers is [`api.remove()`](https://github.com/getavalon/core/blob/14fa89e3487bd5bd02d2adf8bd6e48589e1835cd/avalon/maya/pipeline.py#L501) and it's got access to the name of that `objectSet`. I think we can just add `cmds.delete(container["objectName"])` to that function.
