### ISSUE TITLE
Maintain selection per default

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#255]
### Goal

Simplify Loader interface.

### Motivation

As a general guideline, nothing pipeline related should affect user-facing state, like what is currently selected. At the moment this is implemented at the plug-in level, but could as well be part of the public API such that any loader may modify the selection, and have `avalon.pipeline.load()` restore things back to normal once done.

**Before**

```python
import avalon.maya


class ModelLoader(avalon.maya.Loader):
    def process(self, name, namespace, context, data):
        from maya import cmds

        with avalon.maya.maintained_selection():
            self[:] = cmds.file(
                self.fname,
                namespace=namespace,
                reference=True,
                returnNewNodes=True,
                groupReference=True,
                groupName=namespace + ":" + name
            )
```

**After**

```python
import avalon.maya

class ModelLoader(avalon.maya.Loader):
    def process(self, name, namespace, context, data):
        from maya import cmds

        self[:] = cmds.file(
            self.fname,
            namespace=namespace,
            reference=True,
            returnNewNodes=True,
            groupReference=True,
            groupName=namespace + ":" + name
        )
```

**Comment by BigRoy** [comment]
Wouldn't you, as an artist, want the newly loaded items to be selected?

**Comment by mottosso** [comment]
I'm expecting the artist interface to anything happening this at low-level in the pipeline to be managed elsewhere.

What is important here is that the pipeline never produces any side-effects. In this case, a pipeline mechanism would alter the current selection in Maya. That's a no-no.

For user-facing effects, we should have a look at a separate mechanism, and not rely on side-effects.

**Comment by BigRoy** [comment]
> For user-facing effects, we should have a look at a separate mechanism, and not rely on side-effects.

Sure. I was just expecting for now that the Loader would be that mechanism, as I saw it as the "artist-facing" loader anyway. Though looking forward at an even better alternative.

**Comment by mottosso** [comment]
> as I saw it as the "artist-facing" loader anyway. 

The problem with that is that if we can't rely on consistency in doing pipeline things, we could end up with "work on my machine" kind of errors. For example, if one Loader depends on the selection of something, then another Loader running before it could cause that to behave badly.

> Though looking forward at an even better alternative.

Get those creative juices flowing, we're the ones coming up with that alternative! :)

**Comment by BigRoy** [comment]
> For example, if one Loader depends on the selection of something, then another Loader running before it could cause that to behave badly.

Yes. Makes sense. Safety first.
