### ISSUE TITLE
Clique incompatible with python 3.6

### ISSUE THREAD

**Issue by aardschok** [getavalon/core#270]
## Issue
Clique seems to be written with python 2.7+, resulting in undefined names.
This blocks the publishing of file sequences, more importantly when publishing from the command line as it launches the Pyblish window with python 3.6.

![image](https://user-images.githubusercontent.com/26920875/29509341-308db0e2-8658-11e7-898a-ec49276739f6.png)

## Solution
This issue has been reported to 4degrees (https://gitlab.com/4degrees/clique/issues/29), when library supports python 3.6 this issue should be resolved as well

**Comment by mottosso** [comment]
Fixed with https://github.com/getavalon/core/pull/271
