### ISSUE TITLE
Why Pyblish can be called before Launcher builds the context ?

### ISSUE THREAD

**Issue by davidpower** [getavalon/core#274]
After I set everything up, I can call Launcher with [avalon-setup/avalon.py](https://github.com/getavalon/setup)
which is the entry point of Avalon.
```
$ avalon
```
But I noticed that Pyblish can also be called in [avalon-setup/avalon.py #L301](https://github.com/getavalon/setup/blob/f2341e25c95195c0d6420d31b2b8f12b8ca1a3c9/avalon.py#L301) 
```
$ avalon --publish
```

## Problem
If we call Pyblish before Launcher, isn't there wont be any context exists ?
Shouldn't Pyblish-standalone always be called by Launcher after the Task was chosen ( context built ) ?

**Comment by mottosso** [comment]
This feature is intended for us within a pre-existing context. For example, if you launch a command-line from your Launcher, then it will set up the necessary environment for Pyblish to put files where they need to be.

It's currently used for [render publishing](https://mindbender-studio.github.io/journal/p/week-17/#rendering).

**Comment by davidpower** [comment]
Wow.
So, we still step in Launcher first, then launch a shell which content the context we need, then we call Pyblish-standalone to do the task we want, right?

**Comment by mottosso** [comment]
`avalon.py` is the command-line interface for Avalon, it'll be refactored into this https://github.com/getavalon/cli

Hope this answers your question, welcome to re-open otherwise.
