### ISSUE TITLE
Maya XGen might out of order if the WORKDIR get changed in each task

### ISSUE THREAD

**Issue by davidpower** [getavalon/core#275]
After Launcher launchs Maya, Maya's project-path get set to `AVALON_WORKDIR`.
[core/avalon/maya/pipeline.py](https://github.com/getavalon/core/blob/b76c55cee9f75766a4788ec95322a1044cfc74d9/avalon/maya/pipeline.py#L36)
`AVALON_WORKDIR` depends on which asset and task you chose in the Launcher, so there will be multiple workspace during production.

XGen use project-path to locate the out sourcing map files created or changed during last maya WIP.
So if the maya file which content xgen node, get referenced in to different working stage with different project-path, those out sourcing file link might lost.

<details>
<summary>Some info about why XGen needs project-path stay consistence :</summary>
<br>

Like textures get store in `sourceimages`, Maya `XGen Legacy ` out source lots of maps in every work step, and almost every change made in Maya XGen, will save into those maps, instead of maya file itself.
And the way XGen load those maps, is through relative path :
`project-path/xgen/collections/lots_of_subDir`
More info at [Manage XGen files and directories](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2016/ENU/Maya/files/GUID-E4714F1D-C4F6-49FD-9B89-FDE72CF9296F-htm.html)

</details>

## Problem
`Maya XGen Legacy` needs project-path to stay consistence so it can work properly.
If we need Maya be launched by Launcher, is there any workaround exists for the project-path consistency ?
Or can we skip set project to `AVALON_WORKDIR` ?

**Comment by mottosso** [comment]
> Some info about why XGen needs project-path stay consistence :

Nice use of `<details>`! ;)

> Something like Maya XGen Legacy needs project-path to stay consistence so it can work properly.
If we need Maya be launched by Launcher, is there any workaround exists for the project-path consistency ? Or can we skip set project to AVALON_WORKDIR ?

Just so I understand, how do you mean consistency? What path are you looking for it to set, in place of `AVALON_WORKDIR`?

**Comment by mottosso** [comment]
Do you mean that there needs to already exist a `xgen/` directory in the Maya project dir?

**Comment by mottosso** [comment]
If so, then you can append to the directories it creates via the `default_dirs` of the [Project Execution API](https://getavalon.github.io/2.0/reference/#project-executable-api).

For example, if you are using `avalon-setup`, then you can modify [this](https://github.com/getavalon/setup/blob/master/bin/maya2017.toml#L2). Paths can include subdirectories too, like `xgen/subdir`.

**Comment by davidpower** [comment]
Sorry, I wasn't thinking this right, turns out that all I need to do was using xgen api to export all the `.ptx` maps and xgen description files associated with scene by Pyblish, import them by Loader, and modified the attribute which contents the project-path string in `.xgen` file, during import and export.

In the past, how we work with XGen, was storing all maps for all characters in one xgen-root as Maya's default like 

```
proj/maya/xgen/collections/{char_hair}/{hair_description}/{map_types}/{maps}
```

And now with Avalon, it's just simply changes to something like this

```
proj/work/{character}/maya/xgen/collections/{char_hair}/{hair_description}/{map_types}/{maps}
```

<details>
<summary>Why I freaked out :</summary>
<br>

Without any tool's help, xgen's creation is very fragile, although we did save many versions of maya work file, but the xgen's real change was saved in to those maps, and those maps did not easily save to different version like renaming files, so from time to time, artist often finds out that thier xgen hair was explode or turn to crap, and hard to restore.

After some research, we do have a tool to help us get xgen maps versioned, but we still dealing them in one worksapce.

So I was freaked out by the change of the maya workspace number from one in one project to multiple workspaces in one project, and worried about the xgen path might broken since there is more than one workspace.

But turns out that was just a shadow of pain.

Hope I explained clear about why I got wrong, but if not, no need to bother. 😄 

Because,

</details>

##
**There is no problem now**, at least for XGen, since I can import / export, and modified the root path in the `.xgen` file with xgen api.

With multiple workspace, this might be more safer than ever !

**Comment by davidpower** [comment]
> Do you mean that there needs to already exist a `xgen/` directory in the Maya project dir?

Nah, what I meant was nuts, I was thinking if we can launch Maya with one static working project-path ( one workspace all the way ).

I was trapped in the old way. 😢 

After I read this : [Rythm & Hues pipeline](https://mindbender-studio.github.io/journal/p/week-11/#rythm--hues)
I finally understand the reason why each asset should having their own workspace, and I should stay in this way.

---

Since the true reason ( self-discovery, I think ) I bring up this issue was because lacking the knowledge of asset separation folder structure ( asset oriented ? ), can I change the issue title to something like :
`Why create different workspaces for each task on each asset ?`

Thanks @mottosso !

**Comment by davidpower** [comment]
For unnecessary off topic avoiding and better understanding about the original issue, I did some rephrase and simplify with my comments.
