### ISSUE TITLE
Container content alters when re-opening scene

### ISSUE THREAD

**Issue by aardschok** [getavalon/core#284]
# Issue:
After loading one or multiple assets in Maya, saving the scene and re-opening the scene, the content of the container is not similar to when the assets are first loaded.

```python
# code to test for issue
from maya import cmds
import avalon.maya as maya

for c in maya.ls():
    print cmds.sets(c['objectName'], query=True)
```

**Result after initial loading of asset X**
`[u'hero_02_:body_GEOShape', u'hero_02_:modelDefault', u'hero_02_:HERO_GRP', u'hero_02_:body_GEO', u'hero_02_RN']`

**Result after re-opening scene with loaded asset X**
`[u'hero_02_:modelDefault', u'hero_02_RN']`

To ensure we get a constant result we are currently retrieving the root node of `asset X` and list the relative nodes of that root.

Here is the visual reference from the Node Editor:
![image](https://user-images.githubusercontent.com/26920875/31385274-f2e498fe-adc2-11e7-8599-b48a27e3af49.png)

# Possible cause
We currently think the issue lies in the way the Maya handles its references when opening a scene. This results in the container missing specific information.

**Comment by mottosso** [comment]
Thanks @aardschok, here's how I'd tackle it.

The problem is Maya fails to restore the connection between the container and the reference, likely because the references are created before the container. If so, we can make our own connection that goes *the other way*. From container to node, rather than node to container which is typically the case with traditional Maya Object Sets.

We can still use an objectSet, as they are convenient for hiding from view in the outliner. But we won't use their "grouping" functionality. Instead, we'll make our own connection from container to node.

Like this.

![image](https://user-images.githubusercontent.com/2152766/31386048-606a4348-adbd-11e7-9083-cc39d9e058bf.png)

This will have the same effect, except we'll now have to `ls()` the "contained" nodes ourselves. That's easily done by simply listing the connection coming out of the container.

```python
contained_nodes = cmds.listConnections("containerName.message", destination=True, source=False)
```

**Comment by aardschok** [comment]
Agreed on a different solution

# Solution
By removing the line `cmds.setAttr(container + ".verticesOnlySet", True)` we are able to keep all connections as they were prior to importing. For a clean overview we added a master objectSet calles "AVALON_CONTAINERS" in which all containers will be living. This way the artists are not bugged by the flooding the Outliner with the containers.
This approach also ensures backwards compatibility.

**Comment by mottosso** [comment]
Oh, but wait, does this really solve this issue? I thought the issue was that the inner-containers didn't get their members added correctly?

**Comment by aardschok** [comment]
The issue was that over re-opening the scene, the original nodes were not connected anymore due to the way the reference works within Maya and the settings of the `objectSet`. After we removed that specific line from `avalon.maya.pipelin` the connections were correct after re-opening the scene.

You can do some testing by just removing that line and load an asset in a scene, save it, make a new scene and reopen the old scene, run the code at the end for testing

**results initial loading with line removed**
```python
for c in maya.ls():
    result = cmds.ls(cmds.sets(c["objectName"], query=True), type="transform", long=True)
    print result
# [u'|barrel_001:modelDefaultDefault|barrel_001:barrel_GRP|barrel_001:barrel_GEO', u'|barrel_001:modelDefaultDefault', u'|barrel_001:modelDefaultDefault|barrel_001:barrel_GRP']
```

**results reopening with line removed, script editor output**
``` python
file -f -options "v=0;"  -ignoreVersion  -typ "mayaAscii" -o "C:/Users/User/Documents/development/projects/sandbox/film/s01e01_sh0010/work/setdress/maya/scenes/a.ma";addRecentFile("C:/Users/User/Documents/development/projects/sandbox/film/s01e01_sh0010/work/setdress/maya/scenes/a.ma", "mayaAscii");
// Warning: Frame rate mismatch:  The imported scene frame rate '25 fps' differs from the existing frame rate '24 fps'.
Imported animation keys may not match scene frames and become fractional. // 
// Warning: line 1252: The default image may not be modified. Use the -i/image flag instead. // 
// Read 2 files in  0.054 seconds. // 
// Read 2 files in  0.054 seconds. // 
import avalon.maya as maya

for c in maya.ls():
    result = cmds.ls(cmds.sets(c["objectName"], query=True), type="transform", long=True)
    print result
# [u'|barrel_001:modelDefaultDefault|barrel_001:barrel_GRP|barrel_001:barrel_GEO', u'|barrel_001:modelDefaultDefault', u'|barrel_001:modelDefaultDefault|barrel_001:barrel_GRP']
```

```python
# Use me for some testing
import avalon.maya as maya

for c in maya.ls():
    result = cmds.ls(cmds.sets(c["objectName"], query=True), type="transform", long=True)
    print result
```

**Comment by mottosso** [comment]
Ah! wow, how obscure. Nice find!
