### ISSUE TITLE
Publish Render to Deadline

### ISSUE THREAD

**Issue by Sonegrund** [getavalon/core#286]
### GOAL

To make this work again 

### ISSUE

Nothing happens 

### Re-CREATION

1 - Open a renderScene.
2 - `Create` -> `Render Globals`
3 - `Rendering` -> `Edit Render Globals` And then you choose pool and group etc.
4 -  Load `Publish` and press the publish button 

The expectation is that `Publish` sends/submits the scene to `Deadline`, but nothing happens. It looks suspiciously empty in the `Publish` window. 

![renderglobals_publishsubmit_problem_01](https://user-images.githubusercontent.com/30410513/31483651-86e645f0-af2d-11e7-917c-ca265252e07f.jpg)

**Comment by aardschok** [comment]
As I see from your Pyblish window there are no instances collected to be published so my first question is, do you have a `collect_renderlayer` or `collect_renderglobals` plugin?

**Comment by mottosso** [comment]
This is the config he's using.

- https://github.com/mindbender-studio/config

**Comment by mottosso** [comment]
Are we sure it's supposed to be able to submit just render globals? Shouldn't it need a render layer too?

**Comment by Sonegrund** [comment]
Ahh! Shame on me! Yeah, there needs to be a `renderLayer`. Can't have only the `masterLayer`. Could be nice if there was a message for that perhaps?

**Comment by mottosso** [comment]
Maybe we could include the masterlayer too, unchecked by default?

**Comment by aardschok** [comment]
> Maybe we could include the masterlayer too, unchecked by default?

If we do this I would opt for a renderlayer instance to trigger the renderlayer listing. This way the user MUST make something in order to render so he does not submit renders by accident. Thoughts?

**Comment by mottosso** [comment]
Do you mean they must first create a new layer, in order to publish the masterlayer? Not sure I understand. What does "trigger" and "listing" mean in this context?

**Comment by aardschok** [comment]
**Breakdown:**
User goes to the Create Instance tool and creates an empty instance `renderDefault` or similar. This instance will ensure all render layers get collected as instances which can include the masterLayer.

**Comment by mottosso** [comment]
Ah, yes that makes sense. It's currently called `renderGlobals` which I think is fitting.

**Comment by mottosso** [comment]
Closing this. @aardschok better make a new issue for your proposed feature.

**Comment by BigRoy** [comment]
Unrelated to core, but related to mindbender config. Closing this.
