### ISSUE TITLE
Creator creates instance with wrong subset name when pressing "enter" key too fast

### ISSUE THREAD

**Issue by BigRoy** [getavalon/core#288]
When changing the "subset" name and directly pressing _enter_ to create the instance it will be created with the previously validated name prior to the change. As such it's created with the wrong name.

Instead any form of creation should be disabled until it's confirmed to be fully valid again. The "create" button already does so, but the state it not checked upon `_on_create` when triggered by the enter key.

Should we store something like an internal `valid` state like:
```python
self.state = {
    "valid": False
}
```

Then upon typing it gets invalidated until the data change callback confirms it is valid again and reopens things up for creation. That would make it much safer.

**Comment by BigRoy** [comment]
What do you think of https://github.com/Colorbleed/core/commit/c1d0f11ef7c0b4206283370ed5252f4b7dc6f960 ?

**Comment by mottosso** [comment]
> What do you think of Colorbleed/core@c1d0f11 ?

It's a little explicit, but a good start.
