### ISSUE TITLE
Categories in Loader GUI

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#29]
### Goal

Visually organise assets according to a "category" in the Loader, such as "Environments", "Characters", "Props", etc.

**Comment by mottosso** [comment]
Mimick the look of Launcher.

![image](https://cloud.githubusercontent.com/assets/2152766/25986284/1cf5817e-36e7-11e7-9ed2-df94de4ffbe0.png)

**Comment by BigRoy** [comment]
This is obsolete with the new Loader introduced a long time ago. Among which, see: https://github.com/getavalon/core/pull/198
