### ISSUE TITLE
Avalon tool "cbloader" does not raise to front on "show()"

### ISSUE THREAD

**Issue by BigRoy** [getavalon/core#290]
# Issue

The Avalon `cbloader` does not raise to front when minimized or behind another maya window. As such when clicking "Loader" in the avalon menu it often happens that the window does not get visually shown but is already present behind another window - meaning you'll be searching for it.

# Proposal

We can fix this by adding this to the ` app.py`'s `show()` method:

```python
# If the window is minimized then unminimize it.
if module.window.windowState() & QtCore.Qt.WindowMinimized:
    module.window.setWindowState(QtCore.Qt.WindowActive)
    
# Raise and activate the window
module.window.raise_()             # for MacOS
module.window.activateWindow()     # for Windows
```

This would only run when the window currently exists. :)

As such:
```python

def show(root=None, debug=False, parent=None, use_context=False):
    # Remember window
    if module.window is not None:
        try:
            module.window.show()
        
            # If the window is minimized then unminimize it.
            if module.window.windowState() & QtCore.Qt.WindowMinimized:
                module.window.setWindowState(QtCore.Qt.WindowActive)
                
            # Raise and activate the window
            module.window.raise_()             # for MacOS
            module.window.activateWindow()     # for Windows
            return
        except RuntimeError as e:
            if not e.message.rstrip().endswith("already deleted."):
                raise

            # Garbage collected
            module.window = None

    # ... rest of implementation
```

---

Any comments or better approaches?

**Comment by BigRoy** [comment]
@mottosso what do you think of the proposed method above? :)

**Comment by mottosso** [comment]
Happy for you to make the call on this one, otherwise I'll try and take a look this weekend.

**Comment by BigRoy** [comment]
I implemented it for now in my `dev` branch and it seems convenient. :)

**Comment by BigRoy** [comment]
Funny, I managed to commit it into the wrong app `loader` instead of `cbloader` in a different branch when I just pushed it. In my ` dev` branch I'll fix this back up and move it over. (So you know what's happening if you see a funny commit)
