### ISSUE TITLE
Open up iter_loaders for Avalon

### ISSUE THREAD

**Issue by aardschok** [getavalon/core#295]
## Proposal
Ensure the discovered loaders are available for tools by using the `iter_loaders` from the `cbloader` which has been made by @BigRoy 

## Motivation
After we had the setdress logic implemented I liked the idea of iterating over the discovered loaders to find the suited one.

## Pros
* Single point of definition for the loaders ( removed the need to recreate the logic, hurray )
* Containerize logic is consistent and protected
   * Reduces change of faulty containers ( Manager cannot remove container )
* Allows tools to use more than one representation
   * Data might be loaded through other file extension, only wrote post-load logic

## Cons
* Might slow down loading a bit because of the iteration of loaders

## Code example
```python
loaders = list(lib.iter_loaders(look_representation["_id"]))
Loader = next((i for i in loaders if i.__name__ == "LookLoader"), None)
if Loader is None:
    raise RuntimeError("Could not find LookLoader, this is a bug")

# Reference the look file
with maya.maintained_selection():
    nodes = pipeline.load(Loader, look_representation)
```

**Comment by BigRoy** [comment]
Actually, you can find the loaders through the api with `api.discover(api.Loader)` it just won't tell you which ones are compatible with a specific representation.

The pros and cons are unclear to me, where is this *con* coming from:

> Might slow down loading a bit because of the iteration of loaders

Where will this be used where it's getting slower? :/

**Comment by mottosso** [comment]
I'm no fan of the iterating upwards to find the version, subset and such.

Should we embed some more information into the representation, so that it can be used standalone? What we need to find compatibility is families and representations. Families come from Version (and later Subset). We could simply embed those into the representation.

Maybe embedding them such that they are obviously not at home here.

E.g.

```
{
  "data": {data related to this representation}
  "inherited": {things inherited purely for performance reasons}
}
```

**Comment by aardschok** [comment]
> Actually, you can find the loaders through the api with api.discover(api.Loader) it just won't tell you which ones are compatible with a specific representation.

@BigRoy That is why I support your `iter_loaders`, it allows that possibility. I don't want to rewrite the logic again for just the same purpose. It is already there ( we need to to make our work easy as well ;) )

> I'm no fan of the iterating upwards to find the version, subset and such.

Currently, at least at CB as far as I know, the `representation` has a context attribute which has the following data:

* Project
* Silo
* Asset
* Subset
* Version

As I understood it, this information was used to create a file path from the `representation` itself, please correct me if I am wrong. This information can be sued to fetch the "version, subset and such", this will not alter for any created representation in the database. So @mottosso your `inherited` proposal is already filled.

By using that information from the representation we have a middle ground for the Roy's approach of itering loaders and reduce any queries to the database and therefor removing the need to do upwards  queries.

**Comment by BigRoy** [comment]
Note that the `context` on the `representation` is not required by the schema: https://github.com/getavalon/core/blob/master/avalon/schema/representation-2.0.json

As such you cannot rely on that information being there.

Furthermore, if you want to go down that route just know you'll still need to remain backwards compatible and have it traverse there if the information is missing.

**Comment by aardschok** [comment]
> As such you cannot rely on that information being there.

You already gave the answer here:
> Furthermore, if you want to go down that route just know you'll still need to remain backwards compatible and have it traverse there if the information is missing.

This logic is already in place and is a perfect fallback. We will only have to add a check for content of the data. The data is a dictionary so that will help locate any missing information.

Besides supporting the backwards compatibility I still have to hear a solid response on the idea so I will need to ask it differently : 
* Are you for or against the single point of definition for loading files in to a scene?

**Comment by BigRoy** [comment]
For me the single point of definition is already there. It's the _representation_. 

Whether the logic behind it "confirms" the data from its parents like version, subset and asset or alike is more an optimization if it's to be contained in the representation. To me the logic doesn't differ for the point of entry, it still just takes a representation.

If it's faster by a lot I'd of course be happy to support it.

I think aside from this particular method to get implemented your _pros_ and _cons_ is more about always loading data into maya through the `pipeline.load` method, which I believe is a slightly different issue than opening up the `iter_loaders()` method, but I can see how it's connected to it.

**Comment by mottosso** [comment]
You're right. I'm thinking too much of performance.

What's important I think is the idea that you should be able to pass just a representation to a function, and it should be able to deduct relevant information from where it is in a hierarchy. That I'd like to support.

In fact, I've been thinking of how to standardise that more. I think there's a few too many different argument signatures for functions at the moment, it's tricky to remember them. I like for example how widgets in Qt related to text all take a string to initialise it's textual value. It's intuitive and you don't have to remember which takes what.

But I digress.

I think this issue is about filtering the results of `api.discover()` to some criteria, in this case whether a Creator is compatible with a Representation. The `iter_loaders` looks to work, but isn't there a way we could make that more intuitive? Also does it really need to be an iterator? Typically those are reserved for when each yielded item is expensive and the user might want to abort at some point, before it finishes. But I don't see that being necessary here.

**Comment by BigRoy** [comment]
> I think this issue is about filtering the results of `api.discover()` to some criteria, in this case whether a Creator is compatible with a Representation. The `iter_loaders` looks to work, but isn't there a way we could make that more intuitive? Also does it really need to be an iterator? Typically those are reserved for when each yielded item is expensive and the user might want to abort at some point, before it finishes. But I don't see that being necessary here.

In our case we just want to find a specific compatible loader, which if it's the first one we would be happy to stop the iterator and take it. :) Also, since you could likely try and load hundreds of representations this could get requested often?

**Comment by mottosso** [comment]
Aah, [each iteration](https://github.com/getavalon/core/blob/47a31cabb844c0d75923151d4aa96d931913abde/avalon/tools/cbloader/lib.py#L52) *is* actually quite expensive.. Yes this is a good case for an iterator. I take back what I said about using an iterator.

**Comment by BigRoy** [comment]
Also, to add to this. I believe the `is_compatible_loader` ([here](https://github.com/getavalon/core/blob/47a31cabb844c0d75923151d4aa96d931913abde/avalon/tools/cbloader/lib.py#L36)) logic is also something that should be in the core api.

**Comment by mottosso** [comment]
Is this what we want?

```python
Creators = api.creators_from_representation(creators, representation)
```

**Comment by BigRoy** [comment]
Almost, but then for Loaders, yes. :) Basically that is the `iter_loaders` and it would be an iterator.
Then the `is_compatible_loader` I'd make a standalone logic method since it could potentially be used in the `api.load` method to ensure it's compatible at that point.

```python
Loaders = api.loaders_from_representation(loaders, representation)
```

And I'd reduce it further to:

```
Loaders = api.loaders_from_representation(representation)
```

Where it could take an optional plug-in to filter only considering a pre-specified list of plugins, e.g.:

```python
Loaders = api.loaders_from_representation(representation, plugins=loaders)
```

**Comment by mottosso** [comment]
Let's not make it an iterator. The fact that it's slow right now is a side-effect of having to do the traversal through the database, and we should fix that, not hide it. In fact, even though it's an iterator, it may still go through every available loader until it finds the relevant one, which would make it slow *sometimes*, but not always. That's no good.

> Loaders = api.loaders_from_representation(loaders, representation)

I'd rather not make it implicitly discover loaders from disk. Anything interacting with the disk or database should be kept separate from functions that don't need to. The same goes for most of the lib.py functions you've got there. There's no telling which one of them will contact the database at the moment. Not to mention they are most difficult to test.

If you wouldn't mind, I'd rather we keep it like this. That way it also aligns with Pyblish.

With that, I think we've got a good feature!

**Comment by BigRoy** [comment]
Sure, I get the point. I just imagined it to align with Pyblish because of the `publish` function in `pyblish.util` I suppose. :)

**Comment by BigRoy** [comment]
Here's a draft: https://github.com/getavalon/core/pull/297

**Comment by BigRoy** [comment]
Implemented with https://github.com/getavalon/core/pull/297

The api is `api.loaders_from_representation(Loaders, representation)`

As such to find the loaders for a representation you would:

```python
loaders = api.discover(api.Loader)
loaders  = api.loaders_from_representation(loaders, represenation)
```
