### ISSUE TITLE
Separate Film and Assets in Loader GUI

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#30]
### Goal

Visually separate assets from film in Loader, so as to more easily and quickly find relevant things to load.

**Comment by BigRoy** [comment]
Along with #29 how would you want specifically the Film/Assets separation to look?

As example, in our current case (outside of this toolset) we have a combobox listing all the types, which are _Assets_ or _Film_. Based on which one is selected the items are shown. So their would be a "top-level" decision on what you want to see listed, they would never be shown mixed.

**Comment by mottosso** [comment]
In this pipeline, there is no separation between what is an asset and what
is a shot. Instead, assets are tagged with a 'silo' which I'm most often
happens to be called 'film' and 'assets'.

I'd expect the visual separation to manage any number of silos of any name.

In the launcher, they are made to look like browsing into a directory. The
same could be said for the loader, though a combo box would be OK roo.

**Comment by BigRoy** [comment]
The loader in #198 actually has the silos separated.
