### ISSUE TITLE
Project manager crashes on Add Asset when no Silo created yet

### ISSUE THREAD

**Issue by BigRoy** [getavalon/core#313]
### Issue

The Project Manager crashes whenever "Add Asset" is clicked when no silo is currently active (when no created silo is available)

**Comment by BigRoy** [comment]
We're working on a fix for this in our own repository: https://github.com/Colorbleed/core/pull/16

**Comment by tokejepsen** [comment]
Just ran into this issue. Should we see if we can update the core with your fork?

**Comment by aardschok** [comment]
Looking at the files altered in https://github.com/Colorbleed/core/pull/16 it should be a trivial thing.

**Comment by tokejepsen** [comment]
Think it's better than merging the fork?

**Comment by aardschok** [comment]
If this is the only problem I would keep it contained and I can create a new PR for this from our fork.
I can take a look how much changes our fork might bring just to sure

**Comment by BigRoy** [comment]
Opened a PR to start discussing what's changed, maybe we can start merging soon anyway: https://github.com/getavalon/core/pull/321
