### ISSUE TITLE
Work Files

### ISSUE THREAD

**Issue by tokejepsen** [getavalon/core#319]
**Goal**

Alleviate work files navigation.

**Motivation**

Loading and saving work files can becomes messy fast.

With taking control over where and how work files should be saved, not only makes a tidier file system but also makes users more independent and faster as they don't have to think about files on a disk but can concentrate on content creation.

**Implementation**

Opening/creating work files should happen between choosing which application to launch and actually launching the application.
Most applications are designed to open files directly, so its just a matter of adding to the launch command.

The location of the work files would need to be defined prior to asking the user to open/create.

Choosing which files to open or create, would require some kind of GUI. This could be a simple list with a ```Create``` button.

The naming of the work files would need defining as well. I'm not confident with the Avalon object model, but guess it'll be defined through that somehow.

**Comment by mottosso** [comment]
There's been talk about this at some point and I'm personally not a fan - I think creation need to be as flexible and open ended as possible to account for the many and diverse personalities and preferences of said personalities in a given project - but if it's optional I don't see a problem with it.

**Comment by tokejepsen** [comment]
Think the GUI will need to be as easy as a file browser, if not better.

Have previously done a dialog with ```Open Latest Version``` or ```Open Previous Version```. ```Open Previous Version``` would just simply open a file browser in the folder with all the work files.
