### ISSUE TITLE
Warning on save

### ISSUE THREAD

**Issue by tokejepsen** [getavalon/core#324]
**Problem**

When saving with code a warning appears.

```python
from maya import cmds
cmds.file(rename="temp.ma")
cmds.file(save=True, type="mayaAscii")
```
```
# Warning: avalon.pipeline : Traceback (most recent call last):
  File "C:\Users\admin\avalon-docker\volume\git\avalon-core\avalon\pipeline.py", line 558, in emit
    callback(*args)
TypeError: on_save() takes no arguments (1 given)
```

**Comment by BigRoy** [comment]
What config are you using with that? :)

Can you try registering the on_save callback in such a way that it takes at least a single argument?

**Comment by tokejepsen** [comment]
Sorry, that is the default ```polly``` config.

Does not actually happen for ```colorbleed``` config, so closing this on the core repository.
