### ISSUE TITLE
Workfiles: Gap filling

### ISSUE THREAD

**Issue by tokejepsen** [getavalon/core#334]
**Problem**

When files are not versioned sequentially, the app will start filling in gaps.

Flagged [here](https://github.com/Colorbleed/core/pull/25#issuecomment-415374962)

**Comment by mottosso** [comment]
Do you mean "gaps"? :O

**Comment by aardschok** [comment]
Example:

Versions: v001, v002, v003, v006
Gab version: v004, v005
Next version suggested: v004
Should be version: v007

This of course is a bit of an odd case but the tool should always suggest the highest next version.

**Comment by mottosso** [comment]
I'm so confused; is "gab" a word?

**Comment by aardschok** [comment]
I think it should be __gap__ :') gab is a word but it means small chatter / talk.
