### ISSUE TITLE
AssertionError: This is a bug

### ISSUE THREAD

**Issue by tws0002** [getavalon/core#337]
hi, 

I have this error when selecting batman in avalon-launcher gui. any idea? 
```
Starting avalon-launcher
Registering default actions..
Registering config actions..
Current configuration `polly` has no 'register_launcher_actions'
Registering environment actions..
initialising..
ready
Success
Connecting to batman
Traceback (most recent call last):
  File "K:\SES\Library\spipe\avalon-setup\git\launcher\launcher\control.py", line 199, in push
    handler(index)
  File "K:\SES\Library\spipe\avalon-setup\git\launcher\launcher\control.py", line 277, in on_project_changed
    assert project is not None, "This is a bug"
AssertionError: This is a bug
avalon.py: Finishing up..
```
another question how can I delete miss created project in DB?

Thanks

**Comment by mottosso** [comment]
Thanks for reporting this.

> another question how can I delete miss created project in DB?

This I can answer right away, you need to delete it from the DB by hand. Have a look at RoboMongo for that, it's a graphical interface for Mongo.

**Comment by davidlatwe** [comment]
Hi, @tws0002  I think you may have to try to re-import the example project.
The only way I can reproduce is that the database has been wiped out while Launcher is still open.

**Comment by tws0002** [comment]
@mottosso thanks for the quick reply. I will try RoboMongo.
@davidlatwe you having the same problem?

**Comment by davidlatwe** [comment]
No, I don't have :)
Just trying to reproduce the error based on your message and help to figure out what might happened on your side.

**Comment by BigRoy** [comment]
@tws0002 were you able to resolve this issue?

**Comment by davidlatwe** [comment]
problem fixed :)
closing now
