### ISSUE TITLE
Remove old loader/manager and cleanup dead code

### ISSUE THREAD

**Issue by BigRoy** [getavalon/core#364]
### Issue

Currently the default Loader and Manager you get when running avalon is the old and currently unmaintained one. The current updates being over respectively a year ago and 11 months ago - I believe no one is currently using them anymore.

The new tools however got prefixed `cb` as they were originally a port from the older pipeline at Colorbleed.

To actually run the maintained, up-to-date and new tools newcomers must set the [`AVALON_EARLY_ADOPTER`](https://github.com/getavalon/core/blob/5f552efdc3f5cdf02c320a4aef2a02531444d498/avalon/io.py#L164) environment variable to get the new tools (at least in Maya, the other hosts default to the new one).

_This issue is part of simplifying getting started with Avalon and even some development as old dead code would be removed._

### Proposal

1. Remove the old tools, also remove `avalon.tools.build` which is empty.
2. I believe the new tools should be the standard tools to use.
3. Refactor the tools to remove the `cb` prefix.
4. Remove any fallback to the older loader (since we would remove it)

We need to keep in mind backwards compatibility. Allowing to replace the tool with the new one should cover the Artist use cases, as they will have the same functionality - only through the new standard and updated UI. However, potentially a studio could have written custom code or tools referring to `cbsceneinventory` which should then map to `sceneinventory`. However, since this is not part of the front-facing API I'd say this shouldn't be too big of an issue.

---

Please provide feedback on whether this would be good, why or why not?

**Comment by davidlatwe** [comment]
I like the proposal, maybe we bump the version to `6.0.0` plus a release after these changes ?

**Comment by mottosso** [comment]
My head is in a hundred place this week, but making the Early Adopter features the new default sounds fine to me and is probably much overdue. 👍
