### ISSUE TITLE
Maya set "Hidden in Outliner" for Avalon containers (Maya 2019+)

### ISSUE THREAD

**Issue by BigRoy** [getavalon/core#399]
### Proposal

The default behavior for Avalon in Maya is to have the `AVALON_CONTAINERS` and the containers themselves visible in the outliner. 

However, since Maya 2018 an attribute `hiddenInOutliner` was introduced... yet Autodesk skipped support for it on objectSets. Now, since Maya 2019 it also supports this feature on `objectSet` nodes.

I'm thinking to, for Maya 2019 and up, by default set the `hiddenInOutliner` attribute to to True so:

- The outliner is slightly less cluttered, no `AVALON_CONTAINERS`
- ObjectSets that are insides the loaded container are not nested in `AVALON_CONTAINERS > container > objectSet_is_here` but show just in the outliner as you'd expect. (biggest plus)
- Less likely someone will ever accidentally delete the `AVALON_CONTAINERS` - never happened for us... but it's possible to do so.

To still debug the avalon containers in the scene one can enable `Display > Ignore "Hidden in Outliner"` in the Outliner to still quickly make them visible.

_Note: This is about *loaded* content/containers and not about publish instances. It's the INCOMING containers._

*This behavior would only work moving forward from Maya 2019 upwards*

**Comment by davidlatwe** [comment]
> for Maya 2019 and up, by default set the hiddenInOutliner attribute to to True

+1 :tada: 

> Less likely someone will ever accidentally delete the AVALON_CONTAINERS - never happened for us... but it's possible to do so.

This actually happens here from time to time..., plus, Maya may hang if one select a container that have lots of members in it and the Outliner has set to display set member.

**Comment by BigRoy** [comment]
> Maya may hang if one select a container that have lots of members in it and the Outliner has set to display set member.

This has happened here too, also happens with the Graph Editor I believe. ;)

**Comment by tokejepsen** [comment]
+ 1 :)
