### ISSUE TITLE
Workfiles: doubleclick opens file.

### ISSUE THREAD

**Issue by tokejepsen** [getavalon/core#401]
**Goal**

When double-clicking an item in the workfiles app, it'll open. Same as select > "Open".

**Comment by davidlatwe** [comment]
How about adding this one more goal:
* Accept file save by hitting Enter, currently you need to press `Ok` button to save file.

    ![image](https://user-images.githubusercontent.com/3357009/60982859-8170eb00-a36b-11e9-8695-7942e657df2d.png)

**Comment by BigRoy** [comment]
> When double-clicking an item in the workfiles app, it'll open. Same as select > "Open".

Interesting, for me this already works. See:

![workfiles_double_click_gif](https://user-images.githubusercontent.com/2439881/60983268-f297aa80-a339-11e9-8c8f-2ee0869f90e7.gif)

Did I secretly hack this in without merging it?

> Accept file save by hitting Enter, currently you need to press Ok button to save file.

This could be nice - yes.

**Comment by davidlatwe** [comment]
> Did I secretly hack this in without merging it?

I think this feature has been merged, in #387

**Comment by cameronpd** [comment]
Double clicking to open works for me as well.

**Comment by tokejepsen** [comment]
I can confirm this is already implemented as well :)
