### ISSUE TITLE
Workfiles API redefines built-in `open`

### ISSUE THREAD

**Issue by jasperges** [getavalon/core#407]
The Worfiles API redefines the built-in `open`. That's bad practice and if you're not careful it may lead to issues. Maybe it would be better to rename it to `open_file` or something like this?

https://github.com/getavalon/core/blob/master/avalon/tools/workfiles/app.py#L362
https://github.com/getavalon/core/tree/master/avalon/tools/workfiles#implementing-a-new-host-integration-for-work-files

Every `workio.py` file for the hosts should then be updated as well.

**Comment by BigRoy** [comment]
I'm fine with refactoring it. Thanks for spotting it and pointing it out.
