### ISSUE TITLE
Pymongo collections.save() is deprecated

### ISSUE THREAD

**Issue by BigRoy** [getavalon/core#411]
## Issue

The `avalon.io` module exposes [`save()` from Pymongo Collections, however this seems to be deprecated](https://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.save) in favor of [`replace_one`](https://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.replace_one) and [`insert_one`](https://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.insert_one).

Adding this issue here to ensure we're aware of this deprecation and have any features we implement use `replace_one` and `insert_one` moving forward.

We currently have `replace_one` and `insert_one` exposed via `avalon.io` too, so it's recommended to use those. :)

---

Note that we'll need to swap out `save` in the inventory functions too:
- https://github.com/getavalon/core/blob/a007074c67fffb38e40e829bbd4c266320469853/avalon/inventory.py#L272
- https://github.com/getavalon/core/blob/a007074c67fffb38e40e829bbd4c266320469853/avalon/inventory.py#L302
- https://github.com/getavalon/core/blob/a007074c67fffb38e40e829bbd4c266320469853/avalon/inventory.py#L333

**Comment by davidlatwe** [comment]
I know this one 🙋‍♂ . In the use case of `inventory`, I think we should change to use `replace_one`.
