### ISSUE TITLE
Scene Inventory does not distinguish what Loader is used

### ISSUE THREAD

**Issue by BigRoy** [getavalon/core#454]
### Issue

The **Scene Inventory** does not list what Loader was used to load a specific representation. It solely groups by the exact representation that was loaded, however the exact same published Alembic file could be loaded by a `gpuCacheLoader` *and* a `referenceLoader` for example.

### Proposal

It would be good if the artist could identify which entry was loaded in which way. We could do this in two ways:

1. We include the "Loader" solely as a new column. As such, expanding the hierarchy of a loaded representation shows which loaders were used. This is a trivial light-weight implementation.

2. We include the "Loader" column and additionally also change the grouping to "group by" both representation and loader. That way, without expanding the hierarchies, one can easily identify the Loader used too. This change would be slightly more involved.

I've checked with the artist here who reported it to me and he stated that he'd be fine with 1) where just a column is visible to identify the Loader as one expands it.

**Comment by davidlatwe** [comment]
This should be consider as fixed, right ?

**Comment by BigRoy** [comment]
Sure is. It's implemented as option 1) through #455
