### ISSUE TITLE
Add config for Black or disable the 'Black check' for Hound CI

### ISSUE THREAD

**Issue by jasperges** [getavalon/core#506]
It seems Hound CI recently (see for example [this question](https://gitter.im/getavalon/Lobby?at=5e134ffc316c1473272624ef) by @BigRoy) started to check the code with [Black](https://github.com/psf/black). The only output you get from the Hound is "Black would make changes." So it seems it runs `black --check` on your code.

If this check is wanted, I would suggest to add a config for Black in the repository, unless the default options are totally fine. To add specific config parameters a [`pyproject.toml` file](https://github.com/psf/black#pyprojecttoml) has to be added with configuration options for Black.
As @davidlatwe mentioned [here](https://gitter.im/getavalon/Lobby?at=5e15906dc39503490263b4f1) the default values seem to conflict with PEP8. That is something that could probably be fixed in the config.

How do people feel about this?

**Comment by davidlatwe** [comment]
Add an example for what's conflicting with PEP8:

```python
# original code
name = knob.name()[len(TEMP):]
```

```python
# black formatted
name = knob.name()[len(TEMP) :]
# And my linter highlighted this line and says: "PEP 8 (E203): whitespace before ':' "
```

**Comment by davidlatwe** [comment]
I don't like Black. :angry:

**Comment by jasperges** [comment]
That is really stupid.

I also just noticed that the default line length is 88 (???). As discussed [here](https://github.com/getavalon/core/issues/467) it will be 80 for Avalon (strictly following PEP8).

It also wants me to change `'` to `"`. I really don't like that to be forced...

**Comment by tokejepsen** [comment]
Voting for disabling Black.

**Comment by jasperges** [comment]
Just noticed [this](https://github.com/psf/black#the-black-code-style):
> It is not configurable.

It does have support for YAPF block comments, but it is really ugly to litter your code with them.

I strongly vote for disabling Black.

**Comment by davidlatwe** [comment]
Just found this comment about whitespace before ":" :point_right:  [here](https://github.com/psf/black/issues/315#issuecomment-395457972)

So... the one that is wrong, was my linter which using Flake8...

But even `Black` is *correct* on PEP 8, changing the style just to be on the *right style* side seems unnecessary. :/

Voting for stick with PEP8 + Flake8, disabling Black. :+1:

**Comment by BigRoy** [comment]
👍 - Let's put our new Hound to sleep and revive old black-less Hound. 🐩
