### ISSUE TITLE
Normalise references to external paths

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#54]
### Goal

Enable a flexible project root.

Rather than references, textures and caches being stored as absolute paths, utilise Maya's path resolver to remove the need for absolute paths.

**Before**

```bash
m:\projects\projectA\assets\Bruce\rig.ma
```

**After**

```bash
$PROJECTDIR\assets\Bruce\rig.ma
```

This way, a project can reside anywhere on the artists machine, on any drive, in any subfolder.

### Implementation

On scene save, a nodes of a specific set of types are scanned for paths. Anything with the `PROJECTDIR` variable in it is automatically replaced. The types are references, files and alembic caches. Anything with support for automatic resolving.

**Comment by jadecilcleton** [comment]
Hey Marcus, :)

Im facing this problem a lot, since usually I work remotely. 
I know that texture file nodes easily can store relative paths or variable replacements like you mentioned above . But for reference nodes this seems to have some issues, at least based on what I already tried. 
Do you already have some working solution you found to fix this in other situations outside mindbender pipe? 
If so, could you talk about it here?

Thank u!

**Comment by mottosso** [comment]
Hey Bruno,

> But for reference nodes this seems to have some issues

What issues exactly, what have you tried?

The example project uses these at the moment, and seem to be working fine.

- See [here](https://github.com/mindbender-studio/example/blob/master/projects/hulk/assets/Bruce/work/rigging/marcus/maya/scenes/rig_v001.ma#L5)

Simplest way to try the example project for yourself is to [install it](https://mindbender-studio.github.io/#install), you can do that at home in any directory. Alternatively, [download it](https://github.com/mindbender-studio/example/archive/master.zip) and set it with you existing `mb.bat`.

**Comment by jadecilcleton** [comment]
Nice, thank u for show me the exactly place you intent to replaced the reference path.
If you tested and say it works its fine, but thank u anayway to make it available for anyone to test.

This example uses an asset **modelDefault** inside a **rigDefault** file, where the project is set to the **ROOT** folder in the project ("$projectdir/assets/Bruce/publish/modelDefault/v001/modelDefault.ma"). So both files has identical **$projectdir** variable.

Now, in our current pipeline each shot has the project set inside the shot folder. For instance a **sh_010** in a **pXXX_project** has the project set to:

M:/f01_projects/pXXX_project/film/sh_010/work/animation/Mindbender/maya

Probably in this new scenario you showed me, the shots would need to have the project set to the same **ROOT** folder as the assets, right?

**Comment by mottosso** [comment]
Don't confuse `$PROJECTDIR` with Maya's own project directory. They use the same word "project" but are different.

`$PROJECTDIR` is set via `mb.bat` and has to do with the project you work on, not the Maya project.

That example, and `mb.bat` is using a slightly older version of the pipeline, in the version you use at Mindbender the variable is called `$MINDBENDER_PROJECTPATH`.

- See [here](https://github.com/mindbender-studio/core/blob/master/bin/_mkproject.bat#L36).

Try this, before starting Maya from mb.bat, try this.

```bash
$ mb.bat
$ hulk assets
$ Bruce
$ set MINDBENDER_
```

Replace `hulk` and `Bruce` with a project and asset you have available (that's from the example project). You should be seeing a listing of all variables you can use in your reference and texture nodes.

Such as this.

```bash
MINDBENDER_ASSET=Bruce
MINDBENDER_ASSETPATH=C:\Users\marcus\Dropbox\AF\development\marcus\pyblish\mindbender-example\projects\hulk\assets\Bruce
MINDBENDER_CORE=C:\Users\marcus\Dropbox\AF\development\marcus\pyblish\mindbender-core
MINDBENDER_EXAMPLE=C:\Users\marcus\Dropbox\AF\development\marcus\pyblish\mindbender-example\projects
MINDBENDER_FPS=25
MINDBENDER_PROJECT=hulk
MINDBENDER_PROJECTPATH=C:\Users\marcus\Dropbox\AF\development\marcus\pyblish\mindbender-example\projects\hulk
MINDBENDER_RESOLUTION_HEIGHT=1080
MINDBENDER_RESOLUTION_WIDTH=1920
MINDBENDER_ROOT=C:\Users\marcus\Dropbox\AF\development\marcus\pyblish\mindbender-example\projects\hulk
MINDBENDER_SILO=assets
```

**Comment by mottosso** [comment]
Here's a full example, run this in your Script editor and you should see this:

![image](https://cloud.githubusercontent.com/assets/2152766/25081686/b46fb00e-2343-11e7-9e50-4a6a5522fd81.png)

```python
import os
from maya import cmds, mel

# Create new asset
cmds.file(new=True, force=True)
nodes = cmds.polyCube(name="myCharacter_PLY")

# "Publish" asset
documents_dir = os.path.expanduser("~")
reference_path = os.path.join(documents_dir, "my_reference.ma")
cmds.file(reference_path, exportAll=True, type="mayaAscii", force=True)

# Load asset using absolute path
cmds.file(new=True, force=True)
cmds.file(reference_path, reference=True)

# Load asset using environment variable
cmds.file(new=True, force=True)
os.environ["DOCUMENTS_DIR"] = documents_dir
environment_path = os.path.join("$DOCUMENTS_DIR", "my_reference.ma")
cmds.file(environment_path, reference=True)

# Show reference editor, see path to asset
mel.eval("ReferenceEditor")
```

**Comment by mottosso** [comment]
This is done and works surprisingly well.
