### ISSUE TITLE
Container/Instance relationship

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#64]
### Goal

Associate an Instance with a Container, such that when a Container is deleted the Instance dies with it.

### Implementation

In `remove()`, read custom attribute `children` of Container and remove contained members, only if the member has an equivalent `parentContainer` attribute with itself as value. This would enable a user to "disconnect" the relationship and not have their instances accidentally deleted.

### Motivation

Loading a `mindbender.rig` automatically creates a `mindbender.animation` Instance. This instance should be deleted upon deleting the original rig.

**Comment by mottosso** [comment]
For reference, see `apt-get autoremove` for implementation details. It associates automatic actions performed whilst installing a package, in order to automatically remove them when removing the original package.

**Comment by BigRoy** [comment]
This is obsolete with the implementation of Loader plug-ins that take care of `remove()` themselves, as such it is up to the Config to remove the full instance correctly.
