### ISSUE TITLE
Display Additional Data

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#66]
### Goal

Simplify making informed decisions.

**Data**

- Author
- Version
- Date
- Frames
- Duration
- Pre-roll
- Post-roll

### Inspiration

Colorbleed has got this going.

![image](https://cloud.githubusercontent.com/assets/2152766/23507551/89a8b22a-ff45-11e6-9347-0f9e8beacfc1.png)

**Comment by CalleHalldin** [comment]
ColorBleeds Loader is very sexy i have to say :)

**Comment by BigRoy** [comment]
A first loader port has been merged with #198
