### ISSUE TITLE
mbID on shapes

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#80]
### Goal

Improve logic of `.mbID`.

### Implementation

Transition the `mbID` attribute from residing on nodes of type `transform` to nodes of type `mesh`.

### Motivation

Id's are currently only used for mesh related operations, such as assigning shaders, connecting attributes, but the attribute is stored on the `transform`. This has several drawbacks.

1. When connecting mesh A to mesh B, if the transform of an ID has two shapes, which do we use?
2. When shading one shape differently from another, which do we apply a published shader to?

Additionally, on a technical note Houdini seems to only accept custom attributes via Alembic on shapes.

At the moment we work around it by validating that each transform only has a single mesh, but it's flawed and hacks are starting to manifest themselves throughout the pipeline.

**Comment by BigRoy** [comment]
Just wondering, is there a specific reason  why not every node (regardless of type) gets a `.mbId`?

**Comment by mottosso** [comment]
I think I would need a specific reason to add it to everything. At the moment, only transforms have id's.

**Comment by BigRoy** [comment]
Closing this. 

This is not related to Avalon core but is a discussion that relates to a studio config. If you have any questions or want to continue discussion feel free to do so in this issue, but for now this issue will be closed to reduce redundant clutter.

Note that an example of storing ids on meshes can be found in `colorbleed-config` where it's called `cbId` and generated in Maya. They are [generated on scene save](https://github.com/Colorbleed/colorbleed-config/blob/13842d313f5ccb4875a0a5c294e117a3b3cba1ca/colorbleed/maya/__init__.py#L137) and [validated during publishing](https://github.com/Colorbleed/colorbleed-config/blob/13842d313f5ccb4875a0a5c294e117a3b3cba1ca/colorbleed/plugins/maya/publish/validate_node_ids.py#L8). There are more `cbId` validators, e.g. see all `validate_node_id_*.py` files [here](https://github.com/Colorbleed/colorbleed-config/tree/13842d313f5ccb4875a0a5c294e117a3b3cba1ca/colorbleed/plugins/maya/publish]
