### ISSUE TITLE
Zero out meshes on History Look publish

### ISSUE THREAD

**Issue by mottosso** [getavalon/core#88]
### Goal

Optimise load and file-size on published history lookdev assets.

### Motivation

At the moment, meshes involved in lookdev are exported alongside the asset. Once loaded however, these meshes are entirely discarded. This means publishing includes writing these meshes to disk (megabyetes to gigabytes of data) and later reading these meshes from disk, with no real benefit.

### Implementation

On publish, not only disconnect original input, but temporarily replace it with an empty mesh. This will cause Maya to flush the input with empty space. Once publishing is completed, we can re-connect the original input.

**Comment by BigRoy** [comment]
Closing this.

This is not related to Avalon core but is a discussion that relates to a studio config. If you have any questions or want to continue discussion feel free to do so in this issue, but for now this issue will be closed to reduce redundant clutter.

Also, I believe the following configurations have developed lookdev publishing and none of them (I believe) seem to copy along the model with the lookdev. So they could be a good reference if you are hitting this issue.

- [colorbleed-config](https://github.com/Colorbleed/colorbleed-config)
- [reveries-config](https://github.com/davidlatwe/reveries-config)
- [pype-config](https://github.com/pypeclub/pype)
